# Manual events
name: Test
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: true
        default: 'Hello, World!'
      enable_feature:
        description: 'Enable feature'
        required: false
        type: boolean
        default: false

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          echo "Running tests with input: ${{ inputs.example_input }}"

  job_1: 
    runs-on: ubuntu-latest
    steps:
        run: |
          echo "This is job 1"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
        run: | 
          echo "This is job 2, which ran after job 1"
        

